sudo: required
dist: bionic
language: cpp


cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0


env:
  global:
    - secure: "IeryGzYD1DUkDjFgAscWGQIu7lebz+uN8xi42rWUwBqn8PUpJRoeniEd2/445CdGrX7G3YKDq4YMUFip0n1WyyjmzOQS2dUgJvH3+VU/rtGYoSF8SJkDGXvUl4OTTY0BMGM3+caOb9s91+ZW5C2536e/la0Ti37tu6xq+2URiOZ4ZIxaM+PBJPNJ/e8V9RXPGZxTAlNgpkKrAwv+lVYi7lxqLTTW+0Iu9jilzcAfvZ7tuFvsADNLJ+vEfYSerdeXeq0sma3ez1Z3q+pCyGBv35r/NIsgIH73i9eco0CVNkXmALOQMaw/zRxprHNZxegv0rsEP9/5IDgLXn61ZBOaIrF9Ywi0DTSHWnwoqC/R3XfOX4CXvhttbq6htTepKIfNFsW3SCBqTknil6eOObJaTIu77Y+dU/PpEOmlZI3wq7WKCeMIywNTgGyuTyctFF088XgpqH+ysYOTTN9TOk/U/W29DCT6yEFAuPx/MO24q+v9I5+uwrpIyCdpe2KVOdnIZnegAXYKWw9vjfQRn2n37RKCwkCTG+PWmMMxXgQwuvHzz9z/nV9MkoqbDSwf7pm7y5f+1ggaCBZeGD1Q9N6jx02dTdOeZ7HU9QDWan3YTdqNU1bAp6zDlO76heDOa9EZrRK56FbObFD+60Qm6+ZxzHX4DgS5Q0syOSWbHilKBMk="
    - secure: "WsRnpkAUCnsf4jjf519HlDCXMWObLiG8pm/dQp321LbjjADTcGRqfKRG2cFenK0hG2VrrdnzVWkK4qfzsdQX9OiSZvhqV5ZdVCpSHodhdPWfDxZM1jRJ/oXyjyaE+BwxWRl6Ve1SEbBLMOvdLEiMOt2YbiYE72Hwj5l7qWcVJxQ96L5S160gKA54Efz8ZaLO+lyy0QVh6gdK7DMFZDvFGICH1Yr93drPNFnWmWp3lvEdvomf3F/YCh4M5LMf3EbAjpUssj2r7We2UN6UaXwHfzYFLogOoLLLkrFYYhNgn1jj5rom8MOGj183bKW4jv9Czx7AhjwxRTLUXGKeTQdaaSrZ0t2+Xs4KoqseyT6uQUlE955SfZNdPsjsYrqXHbsC45waSsavlSdKHVLQ20gmY/e+kO982lIIbdrOKzZPjqq9SgI/b2ZdOv0st2ToQHLKbYUIWL8xPt/zA2IqRk0pT7tQgm3uvLB4P+/RAQxdvj7jHz4xXT8mmyHvajbvG4UvJGa9xwn5V58K+xFUxJKYiSDt68ALaFEogQsynkNgNT3xfbF5u/PWOYJ77gbELkg9ExGHCLBLJliVOhEu5sndq46EfSKlifxaG50aj4NKT8SFfykQjhQow/ygs0iqYcBfTM4BoBLVXCFp+yT5YGG+LgYVWq+Gtn51qGJxQYCoMCs="


matrix:
  include:
    # Linux, GCC 5 Vulkan
    - os: linux
      env: COMPILER_C=gcc-5 COMPILER_CXX=g++-5 CMAKE_OPTIONS="-DUSER_PATH_QT=~/opt/qt511" PYPI=false
      compiler: g++
      addons:
        apt:
          packages:
          - g++-5
          - qt511base
          - qt511charts-no-lgpl
          - ca-certificates
          - python2.7
          - mesa-common-dev
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:beineri/opt-qt-5.11.1-bionic'
          # - sourceline: 'ppa:jonathonf/python-2.7'

before_install:
  - sudo apt-get install
  - python --version
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then sudo pip uninstall -y six chardet pyOpenSSL; fi
  - sudo pip install --upgrade pip six pyOpenSSL
  - sudo pip install wheel numpy urllib3==1.23 twine coveralls chardet
  # Setup default versions and override compiler if needed
  - if [[ "${LLVM_VERSION}" == "default" ]]; then LLVM_VERSION=3.9.0; fi
  # Install a recent CMake (unless already installed on OS X)
  - |
    DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
    CMAKE_URL="http://www.cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    export CC=${COMPILER_C} CXX=${COMPILER_CXX}
    source /opt/qt511/bin/qt511-env.sh
    

install:
  # Build everything
  - cd ${TRAVIS_BUILD_DIR}
  - sudo apt-get -qq update
  - sudo apt-get install -y libassimp-dev libglm-dev graphviz libxcb-dri3-0 libxcb-present0 libpciaccess0 cmake libpng-dev libxcb-dri3-dev libx11-dev libx11-xcb-dev libmirclient-dev libwayland-dev libxrandr-dev
  - export VK_VERSION=1.2.131.1
  - wget -O vulkansdk-linux-x86_64-$VK_VERSION.tar.gz https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - tar zxf vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/$VK_VERSION/x86_64

script:
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} ..
  - cd ..
  - ./make.sh
