#version 450

layout (local_size_x = 1024, local_size_y = 1,local_size_z = 1) in;
layout(binding = 0) writeonly buffer Data
{
   float searchdir [];
};
layout(binding = 1) readonly buffer Data2
{
   float delta_a [];
};

layout(push_constant) uniform PushConsts
{
  uint offset1;
  float alpha;
  float rhopdg;
} consts;

void main() {
      searchdir[gl_GlobalInvocationID.x]+=(consts.alpha-consts.rhopdg)*delta_a[consts.offset1+gl_GlobalInvocationID.x];
}
