glslangvalidator -V Scan.comp -o scan.spv --target-env spirv1.3
glslangvalidator -V setDir0.comp -o setDir0.spv --target-env spirv1.3
glslangvalidator -V setDir1.comp -o setDir1.spv --target-env spirv1.3
glslangvalidator -V setdadg.comp -o setdadg.spv --target-env spirv1.3
glslangvalidator -V Apply0.comp -o Apply0.spv --target-env spirv1.3
glslangvalidator -V Apply1.comp -o Apply1.spv --target-env spirv1.3
glslangvalidator -V Apply2.comp -o Apply2.spv --target-env spirv1.3
glslangvalidator -V Apply3.comp -o Apply3.spv --target-env spirv1.3
glslangvalidator -V ApplyVP1.comp -o ApplyVP1.spv --target-env spirv1.3
glslangvalidator -V ApplyVP2_float.comp -o ApplyVP2_float.spv --target-env spirv1.3
glslangvalidator -V ApplyVP2_double.comp -o ApplyVP2_double.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS1.comp -o ApplyLBFGS1.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS2.comp -o ApplyLBFGS2.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS3.comp -o ApplyLBFGS3.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS4.comp -o ApplyLBFGS4.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS5.comp -o ApplyLBFGS5.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS6.comp -o ApplyLBFGS6.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS7.comp -o ApplyLBFGS7.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS8_float.comp -o ApplyLBFGS8_float.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS8_double.comp -o ApplyLBFGS8_double.spv --target-env spirv1.3
glslangvalidator -V ApplyLBFGS9_float.comp -o ApplyLBFGS9_float.spv --target-env spirv1.3
glslangvalidator -V ApplyDepondt1_double.comp -o ApplyDepondt1_double.spv --target-env spirv1.3
glslangvalidator -V ApplyDepondt2_double.comp -o ApplyDepondt2_double.spv --target-env spirv1.3
glslangvalidator -V ApplyDepondt1_float.comp -o ApplyDepondt1_float.spv --target-env spirv1.3
glslangvalidator -V ApplyDepondt2_float.comp -o ApplyDepondt2_float.spv --target-env spirv1.3
glslangvalidator -V ApplyRK4_1_float.comp -o ApplyRK4_1_float.spv --target-env spirv1.3
glslangvalidator -V ApplyRK4_2_float.comp -o ApplyRK4_2_float.spv --target-env spirv1.3
glslangvalidator -V ApplyRK4_3_float.comp -o ApplyRK4_3_float.spv --target-env spirv1.3
glslangvalidator -V ApplyRK4_4_float.comp -o ApplyRK4_4_float.spv --target-env spirv1.3
glslangvalidator -V ApplyCross.comp -o ApplyCross.spv --target-env spirv1.3
glslangvalidator -V ReduceDot.comp -o ReduceDot.spv --target-env spirv1.3
glslangvalidator -V ReduceEnergy.comp -o ReduceEnergy.spv --target-env spirv1.3
glslangvalidator -V ReduceDotFinish.comp -o ReduceDotFinish.spv --target-env spirv1.3
glslangvalidator -V ReduceDotFinishLBFGS.comp -o ReduceDotFinishLBFGS.spv --target-env spirv1.3
glslangvalidator -V ReduceMaxFinish.comp -o ReduceMaxFinish.spv --target-env spirv1.3
glslangvalidator -V ReduceFullDataFinish.comp -o ReduceFullDataFinish.spv --target-env spirv1.3
glslangvalidator -V gradient_double.comp -o gradient_double.spv --target-env spirv1.3
glslangvalidator -V gradient_float.comp -o gradient_float.spv --target-env spirv1.3
glslangvalidator -V oso_calc_gradients.comp -o oso_calc_gradients.spv --target-env spirv1.3
glslangvalidator -V oso_rotate.comp -o oso_rotate.spv --target-env spirv1.3
glslangvalidator -V readSpins.comp -o readSpins.spv --target-env spirv1.3
glslangvalidator -V writeGradient.comp -o writeGradient.spv --target-env spirv1.3
glslangvalidator -V writeSpins.comp -o writeSpins.spv --target-env spirv1.3