#version 450

layout (local_size_x = 1024, local_size_y = 1,local_size_z = 1) in;

layout(binding = 0) writeonly buffer Data
{
   float searchdir [];
};
layout(binding = 1) readonly buffer Data2
{
   float q_vec [];
};
layout(push_constant) uniform PushConsts
{
  float inv_rhody2;
} consts;

void main() {
    searchdir[gl_GlobalInvocationID.x]=  consts.inv_rhody2*q_vec[gl_GlobalInvocationID.x];
}
